name: Update Nife
on: [repository_dispatch, workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/update-nife
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
